### ISSUE TITLE
Create doc pages?

### ISSUE THREAD

**Issue by jo-mueller** [RobinMagnet/pyFM#12]
Hi @RobinMagnet ,

supercool that pyfmaps is now out on PyPi! To improve access, I was thinking about adding something like an API documentation? In principle it's quite easy to set up a little github action, that browses all imported functions and classes from the package and renders the docstrings as API reference papers. I could set it up sometimes if you are interested, it would only require a few clicks on your end in the repository settings to have it hosted at the URL `RobinMagnet.github.io/pyfmaps`

Let me know what you think and happy new year!

**Comment by RobinMagnet** [comment]
Hi Johannes,

I've done a first version, and will update from time to time. I'll try to get the examples in the documentation, but this will take some time.
