### ISSUE TITLE
FMN example?

### ISSUE THREAD

**Issue by daskandalis** [RobinMagnet/pyFM#13]
Is it possible to provide an example of the FMN usage? For example, recreating [Figure 3 of HAGO19](http://www.lix.polytechnique.fr/~maks/papers/limit_shapes_SGP19.pdf)?

**Comment by RobinMagnet** [comment]
Hi,

I have added [an example notebook](https://github.com/RobinMagnet/pyFM/blob/master/examples/functional_map_network/FMN_base.ipynb) on FMN, with code to produce such plot.

**Comment by daskandalis** [comment]
Thank you for this! Would you be willing to share some details of your functional map implementation for this example? I have not been able to obtain consistent bases. What topology was used to construct this FMN?

**Comment by RobinMagnet** [comment]
Hi,

What do you mean about not being able to obtain consistent bases ?

In the example, I had some rough precomputed correspondences and just randomly sampled a set of pairs.
For each pair (i,j), I input both the map `i->j` and `j->i`, which I find to be a good strategy. The network also performs better with many 3-cycles, which might be a good thing to look at.

Also, note that the results are heavily dependent on the quality of the input maps, maybe refining maps individually or via consistent zoomout would help in your case.

**Comment by daskandalis** [comment]
Thanks. I've simply modified your example to combine the FM and FMN examples.

```
calculate_maps = True

process_params = {
    "n_ev": (30, 30),
    "subsample_step": 1,
    "descr_type": "WKS",  # WKS or HKS
}
fit_params = {
    "w_descr": 1e0,
    "w_lap": 1e-2,
    "w_dcomm": 1e-1,
    "w_orient": 0,
}

maps_dict = {}

for map_filename in tqdm(map_files):
    ind2, ind1 = map_filename.split("_to_")
    ind1, ind2 = int(ind1), int(ind2)

    # Indicing starts at 1 in the names, but at 0 on the meshlist
    mesh1, mesh2 = meshlist[ind1 - 1], meshlist[ind2 - 1]

    if calculate_maps:
        
        model = FunctionalMapping(meshlist[ind1-1], meshlist[ind2-1])
        model.preprocess(**process_params, verbose=False)
        model.fit(**fit_params, verbose=False)

        model.zoomout_refine(nit=15, step=1, verbose=False)
        
        FM_12 = model.FM
    else:
        # Load the pointwise map
        p2p_21 = np.loadtxt(f"../data/camel_gallop/maps/{map_filename}", dtype=int)

        # Convert to functional map
        FM_12 = spectral.mesh_p2p_to_FM(p2p_21, mesh1, mesh2, dims=K)

    # Populate the dictionary
    maps_dict[(ind1 - 1, ind2 - 1)] = FM_12
```

Using the uploaded example maps, we get an embedding something like what I expect.

![image](https://github.com/RobinMagnet/pyFM/assets/1887822/b636ab0d-c3bd-476a-b19b-c5a5ea65fa68)

My understanding is that the limit basis $\Phi_0$ can be retrieved from shape _i_ as $\Phi_i \tilde{Y}_i$, where $\Phi$ and $\tilde{Y}$ are respectively the eigen and canonical latent bases. Using the provided FMs, the latent basis derived from any of the shapes is completely consistent.

![image](https://github.com/RobinMagnet/pyFM/assets/1887822/1eab1152-4235-464c-a10b-bb3f234de2d9)

However, when I calculate the maps as above, I cannot get a reasonable and consistent result. In fact, this isn't _so_ bad as long as I used the topology in the example. When I choose a random network or use another topology like a chain, I get much worse results.

![image](https://github.com/RobinMagnet/pyFM/assets/1887822/f260df72-b61c-4ae9-9576-8af62936d825)

The apparent limit basis when calculating from each shape is inconsistent.

![image](https://github.com/RobinMagnet/pyFM/assets/1887822/4a2c5b62-8c57-4ab4-942c-34899e365dcc)

Advice on improving the map computation would be appreciated!

--------------------------------------------------------------------------------------------------------------------------

Calculation of latent bases and plotting.
```
import pyvista as pv

N_plots = 5
ev = 1
zoom = 2

meshlist_sub = [
    int(i) for i in np.linspace(0, len(fmn_model.meshlist) - 1, N_plots)
]

base_eigs_bitmap = []
clb_eigs_bitmap = []
cclb_eigs_bitmap = []

for i in meshlist_sub:
    m = meshlist[i]

    pl = pv.Plotter(off_screen=True)

    scalars = m.eigenvectors[:, ev]

    meshp = pv.make_tri_mesh(m.vertices, m.faces)
    meshp["scalars"] = (scalars - scalars.min()) / np.ptp(scalars)
    pl.add_mesh(meshp, scalars="scalars")
    pl.view_zy()
    pl.remove_scalar_bar()
    pl.show()

    base_eigs_bitmap += [pl.image]

for i in meshlist_sub:
    m = meshlist[i]

    m_ord = np.argsort(m.eigenvalues)
    m_eigv = m.eigenvectors[:, m_ord][:, : fmn_model.M]
    lb0 = (m.eigenvectors[:, : fmn_model.M] @ fmn_model.CLB[i])[:, ev]

    meshp0 = pv.make_tri_mesh(m.vertices, m.faces)
    meshp0["scalars"] = (lb0 - lb0.min()) / np.ptp(lb0)

    pl = pv.Plotter(off_screen=True)
    pl.add_mesh(meshp0, scalars="scalars")
    pl.view_zy()
    pl.remove_scalar_bar()
    pl.show()

    clb_eigs_bitmap += [pl.image]

for i in meshlist_sub:
    m = meshlist[i]

    m_ord = np.argsort(m.eigenvalues)
    m_eigv = m.eigenvectors[:, m_ord][:, : fmn_model.M]
    lb0 = (m_eigv @ fmn_model.CCLB[i])[:, ev]

    meshp0 = pv.make_tri_mesh(m.vertices, m.faces)
    meshp0["scalars"] = (lb0 - lb0.min()) / np.ptp(lb0)

    pl = pv.Plotter(off_screen=True)
    pl.add_mesh(meshp0, scalars="scalars")
    pl.view_zy()
    pl.remove_scalar_bar()
    pl.show()

    cclb_eigs_bitmap += [pl.image]

bitmap_dims = base_eigs_bitmap[0].shape[:2]

fig, axs = plt.subplots(3, N_plots)

for i, (m, m_clb, m_cclb) in enumerate(
    zip(base_eigs_bitmap, clb_eigs_bitmap, cclb_eigs_bitmap)
):
    axs[0, i].imshow(m, interpolation="none")
    axs[1, i].imshow(m_clb, interpolation="none")
    axs[2, i].imshow(m_cclb, interpolation="none")

    axs[0, i].set_axis_off()
    axs[1, i].set_axis_off()
    axs[2, i].set_axis_off()

    if i == 0:
        axs[0, 0].set_title("Mesh eigenbasis")
        axs[1, 0].set_title("CLB")
        axs[2, 0].set_title("CCLB")

plt.gcf().set_size_inches(
    (N_plots * bitmap_dims[0] / 200, 3 * bitmap_dims[0] / 200)
)
plt.subplots_adjust(wspace=0, hspace=0)
```
