### ISSUE TITLE
Support for partial shape matching and point clouds?

### ISSUE THREAD

**Issue by cemoke** [RobinMagnet/pyFM#14]
Hi, thanks for this amazing library. Is there any plan to include partial shape matching and point cloud support? Such as the one presented in Litany, O., Rodolà, E., Bronstein, A. M., & Bronstein, M. M. (2017). Fully Spectral Partial Shape Matching. Computer Graphics Forum, 36(2), 247–258. https://doi.org/10.1111/cgf.13123

**Comment by RobinMagnet** [comment]
Hi,

I don't really plan on supporting these partial shape matching algorithms, since I don't really find them efficient in practice. They have code in Matlab though, which is usable if I recall correctly.
