### ISSUE TITLE
meshplot is not pip-installable

### ISSUE THREAD

**Issue by jo-mueller** [RobinMagnet/pyFM#7]
I think I did a mistake in PR #5 by adding `meshplot` to the `setup.cfg`. It seems that meshplot can only be installed via conda, so has to be installed separately.

Edit: To make sure that the package information (e.g., dependencies, etc) are correct, some automated tests could be added to the repo to make sure that it can install correctly. Such tests could also be used to run some automated benchmark tests whenever something in the codebase is changed to spot potential bugs!

**Comment by RobinMagnet** [comment]
Fixed it thanks.

That's a good idea ! I can easily add this, at least for the most important features like ZoomOut and other conversion methods.
