### ISSUE TITLE
p2p question

### ISSUE THREAD

**Issue by JunshenZheng** [RobinMagnet/pyFM#9]
can I get p2p21 from mesh1 and mesh2 directly? not from functional maps

**Comment by RobinMagnet** [comment]
Hi,

Sorry for the very late answer, I somehow missed this issue.

To answer your question, you will need some initial correspondences for the functional maps framework to work. This can be either dense correspondences, landmarks correspondences, or functions which you expect to be similar.

In practice there are no canonical way to obtain initial correspondence. You can try using shape descriptors, aligning with ICP, using landmarks, learning correspondences, random initialization, etc... It all depends on the data at hand. In the standard functional map pipeline, we use shape descriptors which we expect to be matching.

Once you have these correspondences, you can transform them into a functional map (using the functions in `pyFM.spectral.convert`) and refine them using any spectral algorithm.
